services:
  _defaults:
    autowire: true
    autoconfigure: true

  WebEtDesign\MaintenanceBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection'

  WebEtDesign\MaintenanceBundle\EventSubscriber\MaintenanceSubscriber:
    autowire: true
    arguments:
      - '%wd_maintenance.template%'

  WebEtDesign\MaintenanceBundle\Controller\:
    resource: '../../Controller/*'
    tags: [ 'controller.service_arguments' ]
